# Generated by Django 4.1.7 on 2024-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="name",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
