from django.urls import path
from .views import *

urlpatterns = [
    path("", index, name="home"),
    path("login/", user_login, name="user_login"),
    path("logout/", user_logout, name="logout"),
    path("register/", register, name="register"),
    # path("investment-plans/", investment_plan, name="investment-plans"),
    # path("affiliate-marketing/", affiliate_marketing, name="affiliate-marketing"),
    path("news/", news, name="news"),
    path("contact/", contact, name="contact"),
    path("about/", about, name="about"),
    # path("thesis/", thesis, name="thesis"),
    # path("portfolio/", portfolio, name="portfolio"),
    # path("nfp/", nfp, name="nfp"),
    # path("escrow/", escrow, name="escrow"),
    # path("forex/", forex, name="forex"),
    # path("ieo/", ieo, name="ieo"),
    # path("erc/", erc, name="erc"),
    path("dashboard/", dashboard, name="dashboard"),
    path("profile/", profile, name="profile"),
    path("affiliates/", affiliates, name="affiliates"),
    path("deposits/", deposits, name="deposits"),
    path("investments/", investments, name="investments"),
    path("earnings/", earnings, name="earnings"),
    path("withdrawals/", withdrawals, name="withdrawals"),
    path("compounding/", compounding, name="compounding"),
    path("change_password/", change_password, name="change_password"),
    path("investment/<id>/", investment_detail, name="investment_detail"),
    path("success/", success_view, name="payments_success"),
    path("cancel/", cancel_view, name="payments_cancel"),
    path("forgot_password/", forgot_password, name="forgot_password"),
    path("initiate_payment/", initiate_payment, name="initiate_payment"),
    path("validate_email/", validate_email, name="validate_email"),
    path("kyc/", kyc, name="kyc"),
    path("transaction_start/", transaction_start, name="transaction_start"),
    path("transaction_success/", transaction_success, name="transaction_success"),
    path("complete_cash_to_crypto/", consumate_cash_to_crypto_payment, name="complete_cash_to_crypto_payment"),
    path("complete_crypto_to_cash/", consumate_cryto_to_cash_payment, name="complete_crypto_to_cash_payment")
]
